version: '3.6'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./code:/var/www/html/whocando

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./code:/var/www/html/whocando
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:latest
    ports:
      - "33006:3306"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql-root-pwd'
      MYSQL_DATABASE: 'whocando'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mysql-admin'